export const marketplaceCategories = [
  "Marketing", "Content", "Image generation", "Video generation", "Research", "Coding", "Sales", "Productivity",
];

const template = (id, type, category, title, summary, creator, rating, installs, sections) => ({
  id, type, category, title, summary, creator, rating, installs, version: 1,
  sourceIntent: summary,
  sections: sections.map(([label, content]) => ({ label, content })),
});

export const marketplaceAssets = [
  template("launch-command", "Agent", "Marketing", "Launch Campaign Command Center", "Plans, coordinates, and optimizes a complete multi-channel product launch.", "IntentOS Studio", 4.9, 12840, [["Mission", "Turn a product brief into a measurable launch campaign."], ["Workflow", "Research, position, plan channels, create assets, and optimize."], ["Deliverables", "Campaign brief, calendar, copy system, and KPI dashboard."]]),
  template("cinematic-storyboard", "Skill", "Video generation", "Cinematic Storyboard Director", "Transforms a short concept into shot-by-shot direction ready for AI video tools.", "Mira Chen", 4.8, 9360, [["Input", "Concept, duration, format, audience, and visual references."], ["Method", "Build narrative beats, camera language, lighting, and transitions."], ["Output", "Production-ready scene and shot list with generation prompts."]]),
  template("visual-campaign", "Prompt", "Image generation", "Visual Campaign Art Director", "Creates consistent premium image prompts across an entire brand campaign.", "Northstar Labs", 4.9, 11220, [["Role", "Act as a senior campaign art director."], ["Constraints", "Preserve brand codes, subject consistency, composition, and lighting."], ["Output", "A reusable master prompt plus channel-specific variations."]]),
  template("content-engine", "Agent", "Content", "Founder Content Engine", "Turns one weekly insight into a coordinated month of high-authority content.", "Signal Works", 4.7, 7810, [["Mission", "Build authentic founder-led distribution."], ["Workflow", "Extract insight, create pillars, adapt formats, and schedule."], ["Guardrails", "Keep the founder voice specific, credible, and non-generic."]]),
  template("deep-research", "Agent", "Research", "Evidence-First Research Analyst", "Investigates complex questions and produces decision-ready, source-aware briefs.", "IntentOS Studio", 4.8, 10640, [["Mission", "Produce reliable research for high-quality decisions."], ["Method", "Define claims, gather evidence, triangulate, and flag uncertainty."], ["Output", "Executive brief, evidence table, risks, and recommendations."]]),
  template("react-review", "Skill", "Coding", "Senior React Code Reviewer", "Reviews React changes for correctness, accessibility, performance, and maintainability.", "DevFoundry", 4.9, 14510, [["Scope", "React components, hooks, state, data flow, and CSS."], ["Review", "Prioritize bugs and user impact before style preferences."], ["Output", "Ranked findings with evidence and practical fixes."]]),
  template("sales-discovery", "Prompt", "Sales", "Strategic Discovery Call Planner", "Prepares sharp discovery questions tailored to a prospect, market, and deal stage.", "Revenue Craft", 4.7, 6240, [["Context", "Use account, persona, pains, triggers, and existing signals."], ["Approach", "Sequence questions from situation to business impact."], ["Output", "Call plan, questions, hypotheses, and next-step criteria."]]),
  template("weekly-operator", "Agent", "Productivity", "Weekly Operations Copilot", "Converts scattered priorities into a focused execution plan with follow-through.", "Flow State", 4.6, 5890, [["Mission", "Protect the highest-leverage work each week."], ["Workflow", "Capture, prioritize, schedule, identify blockers, and review."], ["Output", "Weekly plan, daily focus blocks, and risk alerts."]]),
  template("seo-brief", "Skill", "Content", "Search-Led Content Brief", "Builds comprehensive SEO briefs without sacrificing original insight or readability.", "Organic Studio", 4.8, 8740, [["Research", "Map intent, subtopics, questions, and competitive gaps."], ["Structure", "Create a logical narrative before keyword placement."], ["Output", "Brief, outline, evidence needs, links, and quality checklist."]]),
  template("product-spec", "Prompt", "Coding", "Production Feature Spec", "Turns a rough product idea into an implementation-ready engineering specification.", "DevFoundry", 4.8, 13190, [["Goal", "Remove ambiguity before implementation begins."], ["Coverage", "User stories, states, data, edge cases, accessibility, and telemetry."], ["Output", "Structured spec with acceptance criteria and rollout plan."]]),
];
